import type { Campaign, Case, CaseSummary, VendorProfile } from "@/types/sentinel";

/**
 * Demo Mode fixtures. Used ONLY when VITE_DEMO_MODE=true, and always surfaced
 * with a visible "Demo data" pill. Static sample cases — never live telemetry.
 */

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();

export const demoCases: Case[] = [
  {
    id: "c-1042",
    case_number: "SM-1042",
    subject: "Updated remittance details for invoice INV-88213",
    sender: "accounts@aster-supplyco.com",
    threat_class: "invoice_fraud",
    risk_score: 94,
    severity: "critical",
    decision: "pending",
    assigned_action: "Hold payment",
    vendor: "Supply Co Industrial",
    amount_at_risk: 184320,
    currency: "USD",
    created_at: hoursAgo(3),
    confidence: 0.96,
    decision_banner: "Hold payment recommended — vendor identity mismatch detected",
    recipients: ["ap@astermanufacturing.com"],
    body_preview:
      "Please note our banking details have changed effective immediately. Kindly remit the outstanding balance of $184,320.00 to the account below to avoid service interruption. Treat this as confidential until the transfer clears.",
    evidence: {
      intent: {
        classification: "invoice_fraud",
        model_confidence: 0.96,
        signals: [
          { label: "Banking details change request", severity: "critical", weight: 0.34 },
          { label: "Urgency pressure language", severity: "high", weight: 0.19 },
          {
            label: "Requests confidentiality until transfer clears",
            severity: "high",
            weight: 0.14,
          },
        ],
      },
      sender_identity: {
        from_address: "accounts@aster-supplyco.com",
        display_name: "Supply Co Accounts",
        reply_to: "accounts.finance@supplyco-billing.net",
        return_path: "bounce@mx41.supplyco-billing.net",
        auth: { spf: "softfail", dkim: "fail", dmarc: "fail" },
        trusted_vendor: "Supply Co Industrial",
        vendor_domain_match: false,
        notes: [
          { label: "Reply-To domain differs from From domain", severity: "critical" },
          { label: "Look-alike domain registered 11 days ago", severity: "high" },
        ],
      },
      financial: {
        invoice_amount: 184320,
        currency: "USD",
        bank_account_last4: "7741",
        bank_account_known: false,
        payment_change_requested: true,
        beneficiary: "SUPPLYCO TRADING LTD",
        notes: [{ label: "Beneficiary name differs from contracted entity", severity: "high" }],
      },
      technical: {
        urls: [
          "https://supplyco-billing.net/invoice/88213",
          "https://cdn.supplyco-billing.net/doc",
        ],
        domains: ["supplyco-billing.net", "mx41.supplyco-billing.net"],
        relay_ips: ["45.147.230.18", "185.220.101.44", "10.14.2.7"],
        attachments: [
          {
            filename: "INV-88213-revised.pdf",
            mime_type: "application/pdf",
            size_bytes: 184233,
            sha256: "9f2c41ab7d0e5b8c1a44f9e2b6d7c3018a5e4f9b2c7d1e3a6b8f0c2d4e6a8b1c",
            suspicious: true,
          },
        ],
      },
    },
    timeline: [
      {
        order: 1,
        title: "Bank account never seen for this vendor",
        description:
          "Account ending 7741 does not match approved suffixes 4412 or 8890 for Supply Co Industrial.",
        severity: "critical",
        weight: 0.31,
      },
      {
        order: 2,
        title: "Reply-To redirects off-domain",
        description:
          "Replies route to supplyco-billing.net, not the contracted vendor domain supplyco.com.",
        severity: "critical",
        weight: 0.24,
      },
      {
        order: 3,
        title: "Authentication failures on sending path",
        description:
          "DKIM fail, DMARC fail, SPF softfail. Message did not originate from vendor infrastructure.",
        severity: "high",
        weight: 0.18,
      },
      {
        order: 4,
        title: "Payment-change language detected",
        description: "Classifier flagged remittance-change phrasing combined with urgency markers.",
        severity: "high",
        weight: 0.15,
      },
      {
        order: 5,
        title: "Indicator overlap with active campaign",
        description: "Reply-To address and bank suffix also appear in case SM-1039.",
        severity: "medium",
        weight: 0.12,
      },
    ],
    relay_path: [
      {
        index: 1,
        host: "mx41.supplyco-billing.net",
        ip: "45.147.230.18",
        asn: "AS204601 (hosting provider)",
        country: "NL",
        timestamp: hoursAgo(3.1),
        suspicious: true,
      },
      {
        index: 2,
        host: "relay-7.mailhop.example",
        ip: "185.220.101.44",
        asn: "AS60729",
        country: "DE",
        timestamp: hoursAgo(3.05),
        suspicious: true,
      },
      {
        index: 3,
        host: "mail.astermanufacturing.com",
        ip: "10.14.2.7",
        asn: "internal",
        country: "US",
        timestamp: hoursAgo(3),
      },
    ],
    campaign_id: "camp-04",
    campaign_graph: {
      nodes: [
        { id: "e1", label: "SM-1042", type: "email", suspicious: true },
        { id: "e2", label: "SM-1039", type: "email" },
        { id: "d1", label: "supplyco-billing.net", type: "domain", suspicious: true },
        { id: "u1", label: "/invoice/88213", type: "url" },
        { id: "r1", label: "accounts.finance@…", type: "reply_to", suspicious: true },
        { id: "b1", label: "acct ••••7741", type: "bank_account", suspicious: true },
        { id: "a1", label: "INV-88213-revised.pdf", type: "attachment" },
      ],
      edges: [
        { source: "e1", target: "d1", suspicious: true },
        { source: "e1", target: "r1", suspicious: true },
        { source: "e1", target: "b1", suspicious: true },
        { source: "e1", target: "u1" },
        { source: "e1", target: "a1" },
        { source: "e2", target: "r1", suspicious: true },
        { source: "e2", target: "b1", suspicious: true },
      ],
    },
    actions: [],
  },
  {
    id: "c-1041",
    triage_minutes: 21,
    case_number: "SM-1041",
    subject: "Urgent wire needed before board call",
    sender: "m.calder@astermanufactoring.com",
    threat_class: "ceo_impersonation",
    risk_score: 89,
    severity: "critical",
    decision: "escalated",
    assigned_action: "Escalated to security",
    vendor: "—",
    amount_at_risk: 96500,
    currency: "USD",
    created_at: hoursAgo(9),
    confidence: 0.92,
    decision_banner: "Hold payment recommended — executive impersonation via look-alike domain",
    recipients: ["treasury@astermanufacturing.com"],
    body_preview:
      "I am in back-to-back meetings ahead of the board call. Please process a wire of $96,500 today and confirm by reply only. Do not loop in the wider finance list.",
    evidence: {
      intent: {
        classification: "ceo_impersonation",
        model_confidence: 0.92,
        signals: [
          { label: "Executive display name with external domain", severity: "critical" },
          { label: "Secrecy instruction", severity: "high" },
          { label: "Same-day wire request", severity: "high" },
        ],
      },
      sender_identity: {
        from_address: "m.calder@astermanufactoring.com",
        display_name: "Marcus Calder (CEO)",
        reply_to: "m.calder.office@mailrelay-secure.com",
        return_path: "bounce@mailrelay-secure.com",
        auth: { spf: "pass", dkim: "none", dmarc: "fail" },
        vendor_domain_match: false,
        notes: [
          { label: "Domain differs from corporate domain by one character", severity: "critical" },
        ],
      },
      financial: {
        invoice_amount: 96500,
        currency: "USD",
        bank_account_last4: "2210",
        bank_account_known: false,
        payment_change_requested: true,
        beneficiary: "CALDER ADVISORY SERVICES",
      },
      technical: {
        urls: [],
        domains: ["astermanufactoring.com", "mailrelay-secure.com"],
        relay_ips: ["91.219.236.7", "10.14.2.7"],
        attachments: [],
      },
    },
    timeline: [
      {
        order: 1,
        title: "Look-alike corporate domain",
        description: "astermanufactoring.com is a one-character variant of the corporate domain.",
        severity: "critical",
        weight: 0.3,
      },
      {
        order: 2,
        title: "Reply-To off corporate infrastructure",
        description: "Replies route to mailrelay-secure.com, unrelated to the organization.",
        severity: "critical",
        weight: 0.26,
      },
      {
        order: 3,
        title: "DMARC failure",
        description: "The message fails DMARC alignment for the impersonated identity.",
        severity: "high",
        weight: 0.2,
      },
    ],
    relay_path: [
      {
        index: 1,
        host: "smtp.mailrelay-secure.com",
        ip: "91.219.236.7",
        asn: "AS49505",
        country: "RU",
        timestamp: hoursAgo(9.1),
        suspicious: true,
      },
      {
        index: 2,
        host: "mail.astermanufacturing.com",
        ip: "10.14.2.7",
        asn: "internal",
        country: "US",
        timestamp: hoursAgo(9),
      },
    ],
    campaign_id: "camp-07",
    actions: [],
  },
  {
    id: "c-1039",
    triage_minutes: 34,
    case_number: "SM-1039",
    subject: "Invoice INV-88060 — amended payment instructions",
    sender: "billing@supplyco-billing.net",
    threat_class: "invoice_fraud",
    risk_score: 87,
    severity: "critical",
    decision: "payment_held",
    assigned_action: "Payment held",
    vendor: "Supply Co Industrial",
    amount_at_risk: 61240,
    currency: "USD",
    created_at: hoursAgo(28),
    confidence: 0.9,
    decision_banner: "Payment held — bank account not on the approved vendor list",
    recipients: ["ap@astermanufacturing.com"],
    body_preview:
      "Kindly find amended payment instructions for invoice INV-88060. Our previous account is under audit and cannot receive funds this week.",
    evidence: {
      intent: {
        classification: "invoice_fraud",
        model_confidence: 0.9,
        signals: [
          { label: "Account-under-audit pretext", severity: "high" },
          { label: "Amended payment instructions", severity: "critical" },
        ],
      },
      sender_identity: {
        from_address: "billing@supplyco-billing.net",
        reply_to: "accounts.finance@supplyco-billing.net",
        auth: { spf: "fail", dkim: "fail", dmarc: "fail" },
        trusted_vendor: "Supply Co Industrial",
        vendor_domain_match: false,
      },
      financial: {
        invoice_amount: 61240,
        currency: "USD",
        bank_account_last4: "7741",
        bank_account_known: false,
        payment_change_requested: true,
        beneficiary: "SUPPLYCO TRADING LTD",
      },
      technical: {
        urls: ["https://supplyco-billing.net/pay/88060"],
        domains: ["supplyco-billing.net"],
        relay_ips: ["45.147.230.18", "10.14.2.7"],
        attachments: [],
      },
    },
    timeline: [
      {
        order: 1,
        title: "Shared fraudulent bank account",
        description: "Account ending 7741 matches the account used in case SM-1042.",
        severity: "critical",
        weight: 0.33,
      },
      {
        order: 2,
        title: "All authentication checks failed",
        description: "SPF, DKIM and DMARC all fail for supplyco-billing.net.",
        severity: "high",
        weight: 0.22,
      },
    ],
    relay_path: [
      {
        index: 1,
        host: "mx41.supplyco-billing.net",
        ip: "45.147.230.18",
        asn: "AS204601",
        country: "NL",
        timestamp: hoursAgo(28.1),
        suspicious: true,
      },
      {
        index: 2,
        host: "mail.astermanufacturing.com",
        ip: "10.14.2.7",
        country: "US",
        timestamp: hoursAgo(28),
      },
    ],
    campaign_id: "camp-04",
    actions: [],
  },
  {
    id: "c-1037",
    case_number: "SM-1037",
    subject: "Purchase order PO-55129 revision for approval",
    sender: "procurement@harborline-metals.com",
    threat_class: "invoice_fraud",
    risk_score: 97,
    severity: "critical",
    decision: "pending",
    assigned_action: "Hold payment",
    vendor: "Harborline Metals",
    amount_at_risk: 38900,
    currency: "USD",
    created_at: hoursAgo(1),
    confidence: 0.97,
    decision_banner: "Hold payment recommended — genuine vendor relationship hijacked",
    recipients: ["ap@astermanufacturing.com"],
    body_preview:
      "Attached is the revised purchase order. Our prior account is temporarily unavailable. Please use the updated beneficiary below and confirm the payment release today.",
    evidence: {
      intent: {
        classification: "invoice_fraud",
        model_confidence: 0.97,
        signals: [
          {
            label: "Payment beneficiary and account change request",
            severity: "critical",
            weight: 0.31,
          },
          { label: "Urgent same-day release request", severity: "high", weight: 0.18 },
          { label: "Trusted vendor language pattern changed", severity: "high", weight: 0.16 },
        ],
      },
      sender_identity: {
        from_address: "procurement@harborline-metals.com",
        display_name: "Maya Chen — Procurement",
        reply_to: "payments@harborline-remit.co",
        return_path: "procurement@harborline-metals.com",
        auth: { spf: "pass", dkim: "pass", dmarc: "pass" },
        trusted_vendor: "Harborline Metals",
        vendor_domain_match: true,
        notes: [
          { label: "Authenticated from the genuine vendor domain", severity: "safe" },
          { label: "Reply-To is new for this trusted contact", severity: "critical" },
        ],
      },
      financial: {
        invoice_amount: 38900,
        currency: "USD",
        bank_account_last4: "5518",
        bank_account_known: false,
        payment_change_requested: true,
        beneficiary: "HARBORLINE METALS GROUP",
      },
      technical: {
        urls: [],
        domains: ["harborline-metals.com", "harborline-remit.co"],
        relay_ips: ["198.51.100.77", "10.14.2.7"],
        attachments: [
          {
            filename: "PO-55129-rev2.pdf",
            mime_type: "application/pdf",
            size_bytes: 92211,
            sha256: "b1e8c40d7a2f96531c8de40a7b2f61c9d05e83a47f2b6c91d3e70a58f4c2b6d9",
          },
        ],
      },
      vendor_relationship: {
        trusted_domain: "harborline-metals.com",
        known_contact: "procurement@harborline-metals.com",
        approved_bank_suffixes: ["••••1142", "••••6630"],
        normal_recipients: ["ap@astermanufacturing.com"],
      },
    },
    timeline: [
      {
        order: 1,
        title: "New beneficiary account from a genuine vendor mailbox",
        description:
          "Account ending 5518 is not on the approved list for Harborline Metals, despite SPF, DKIM and DMARC passing.",
        severity: "critical",
        weight: 0.31,
      },
      {
        order: 2,
        title: "New Reply-To breaks the trusted contact pattern",
        description:
          "Replies now route to harborline-remit.co, a destination never used by this established vendor contact.",
        severity: "critical",
        weight: 0.26,
      },
      {
        order: 3,
        title: "Payment behavior departs from the vendor baseline",
        description:
          "This contact normally sends purchase-order updates to Accounts Payable and has never requested a same-day beneficiary change.",
        severity: "high",
        weight: 0.2,
      },
    ],
    relay_path: [
      {
        index: 1,
        host: "mail.harborline-metals.com",
        ip: "198.51.100.77",
        asn: "AS64500",
        country: "US",
        timestamp: hoursAgo(40.1),
      },
      {
        index: 2,
        host: "mail.astermanufacturing.com",
        ip: "10.14.2.7",
        country: "US",
        timestamp: hoursAgo(40),
      },
    ],
    actions: [],
  },
  {
    id: "c-1035",
    triage_minutes: 47,
    case_number: "SM-1035",
    subject: "Mailbox storage exceeded — verify account",
    sender: "support@mailquota-alerts.com",
    threat_class: "credential_phishing",
    risk_score: 78,
    severity: "high",
    decision: "confirmed_threat",
    assigned_action: "Confirmed threat",
    vendor: "—",
    created_at: hoursAgo(54),
    confidence: 0.88,
    decision_banner: "Confirmed threat — credential harvesting page linked in message",
    recipients: ["finance-team@astermanufacturing.com"],
    body_preview:
      "Your mailbox has exceeded its storage quota. Verify your account within 24 hours to avoid interruption of incoming mail.",
    evidence: {
      intent: {
        classification: "credential_phishing",
        model_confidence: 0.88,
        signals: [
          { label: "Credential capture form on linked page", severity: "critical" },
          { label: "24-hour deadline pressure", severity: "high" },
        ],
      },
      sender_identity: {
        from_address: "support@mailquota-alerts.com",
        auth: { spf: "fail", dkim: "none", dmarc: "fail" },
        vendor_domain_match: false,
      },
      financial: {},
      technical: {
        urls: ["https://mailquota-alerts.com/verify?u=finance"],
        domains: ["mailquota-alerts.com"],
        relay_ips: ["198.51.100.24", "10.14.2.7"],
        attachments: [],
      },
    },
    timeline: [
      {
        order: 1,
        title: "Credential harvesting page",
        description:
          "Linked page replicates the corporate sign-in screen and posts to an external host.",
        severity: "critical",
        weight: 0.35,
      },
    ],
    relay_path: [
      {
        index: 1,
        host: "smtp.mailquota-alerts.com",
        ip: "198.51.100.24",
        asn: "AS39572",
        country: "PA",
        timestamp: hoursAgo(54.1),
        suspicious: true,
      },
      {
        index: 2,
        host: "mail.astermanufacturing.com",
        ip: "10.14.2.7",
        country: "US",
        timestamp: hoursAgo(54),
      },
    ],
    campaign_id: "camp-02",
    actions: [],
  },
  {
    id: "c-1031",
    case_number: "SM-1031",
    subject: "Shipping documents attached (BL-4471)",
    sender: "logistics@northline-freight.com",
    threat_class: "malware_delivery",
    risk_score: 66,
    severity: "high",
    decision: "pending",
    assigned_action: "—",
    vendor: "Northline Freight",
    created_at: hoursAgo(78),
    confidence: 0.79,
    decision_banner: "Review required — archive attachment contains executable content",
    recipients: ["logistics@astermanufacturing.com"],
    body_preview:
      "Please find the shipping documents for bill of lading BL-4471 attached. Extract the archive to view the signed copy.",
    evidence: {
      intent: {
        classification: "malware_delivery",
        model_confidence: 0.79,
        signals: [{ label: "Archive with double extension", severity: "high" }],
      },
      sender_identity: {
        from_address: "logistics@northline-freight.com",
        auth: { spf: "pass", dkim: "pass", dmarc: "none" },
        trusted_vendor: "Northline Freight",
        vendor_domain_match: true,
      },
      financial: {},
      technical: {
        urls: [],
        domains: ["northline-freight.com"],
        relay_ips: ["203.0.113.9", "10.14.2.7"],
        attachments: [
          {
            filename: "BL-4471.pdf.zip",
            mime_type: "application/zip",
            size_bytes: 421889,
            sha256: "3b7d9a1c5e0f2846ab19d4c7e5f83b0c6d2a9e1f4c7b0d3a6e9f2c5b8d1a4e7f",
            suspicious: true,
          },
        ],
      },
    },
    timeline: [
      {
        order: 1,
        title: "Suspicious attachment structure",
        description: "Archive presents as a PDF but contains a script payload.",
        severity: "high",
        weight: 0.26,
      },
    ],
    relay_path: [
      {
        index: 1,
        host: "mail.northline-freight.com",
        ip: "203.0.113.9",
        asn: "AS64511",
        country: "CA",
        timestamp: hoursAgo(78.1),
      },
      {
        index: 2,
        host: "mail.astermanufacturing.com",
        ip: "10.14.2.7",
        country: "US",
        timestamp: hoursAgo(78),
      },
    ],
    actions: [],
  },
  {
    id: "c-1029",
    triage_minutes: 26,
    case_number: "SM-1029",
    subject: "Payroll portal password expiring today",
    sender: "hr-notice@payrollcentral-secure.com",
    threat_class: "credential_phishing",
    risk_score: 74,
    severity: "high",
    decision: "escalated",
    assigned_action: "Escalated to security",
    vendor: "—",
    created_at: hoursAgo(96),
    confidence: 0.85,
    decision_banner: "Escalated — payroll credential phishing targeting finance staff",
    recipients: ["payroll@astermanufacturing.com"],
    body_preview:
      "Your payroll portal password expires today. Sign in to renew your credentials and keep direct deposit active.",
    evidence: {
      intent: {
        classification: "credential_phishing",
        model_confidence: 0.85,
        signals: [{ label: "Payroll-themed credential lure", severity: "high" }],
      },
      sender_identity: {
        from_address: "hr-notice@payrollcentral-secure.com",
        auth: { spf: "softfail", dkim: "fail", dmarc: "fail" },
        vendor_domain_match: false,
      },
      financial: {},
      technical: {
        urls: ["https://payrollcentral-secure.com/renew"],
        domains: ["payrollcentral-secure.com"],
        relay_ips: ["203.0.113.201", "10.14.2.7"],
        attachments: [],
      },
    },
    timeline: [
      {
        order: 1,
        title: "Recently registered lure domain",
        description: "payrollcentral-secure.com was registered six days before this message.",
        severity: "high",
        weight: 0.24,
      },
    ],
    relay_path: [
      {
        index: 1,
        host: "smtp.payrollcentral-secure.com",
        ip: "203.0.113.201",
        asn: "AS20473",
        country: "SG",
        timestamp: hoursAgo(96.1),
        suspicious: true,
      },
      {
        index: 2,
        host: "mail.astermanufacturing.com",
        ip: "10.14.2.7",
        country: "US",
        timestamp: hoursAgo(96),
      },
    ],
    campaign_id: "camp-02",
    actions: [],
  },
  {
    id: "c-1028",
    triage_minutes: 12,
    case_number: "SM-1028",
    subject: "Quarterly statement — no action required",
    sender: "billing@meridian-utilities.com",
    threat_class: "benign",
    risk_score: 9,
    severity: "safe",
    decision: "safe",
    assigned_action: "Marked safe",
    vendor: "Meridian Utilities",
    amount_at_risk: 4210,
    currency: "USD",
    created_at: hoursAgo(120),
    confidence: 0.94,
    decision_banner: "No action — sender and banking details match the vendor record",
    recipients: ["ap@astermanufacturing.com"],
    body_preview:
      "Attached is your quarterly statement. No payment action is required; the balance is settled by direct debit.",
    evidence: {
      intent: { classification: "benign", model_confidence: 0.94, signals: [] },
      sender_identity: {
        from_address: "billing@meridian-utilities.com",
        auth: { spf: "pass", dkim: "pass", dmarc: "pass" },
        trusted_vendor: "Meridian Utilities",
        vendor_domain_match: true,
      },
      financial: {
        invoice_amount: 4210,
        currency: "USD",
        bank_account_last4: "9032",
        bank_account_known: true,
        payment_change_requested: false,
      },
      technical: {
        urls: [],
        domains: ["meridian-utilities.com"],
        relay_ips: ["10.14.2.7"],
        attachments: [],
      },
    },
    timeline: [],
    relay_path: [
      {
        index: 1,
        host: "mail.astermanufacturing.com",
        ip: "10.14.2.7",
        country: "US",
        timestamp: hoursAgo(120),
      },
    ],
    actions: [],
  },
];

export const demoCaseSummaries: CaseSummary[] = demoCases.map((c) => ({
  id: c.id,
  case_number: c.case_number,
  subject: c.subject,
  sender: c.sender,
  threat_class: c.threat_class,
  risk_score: c.risk_score,
  severity: c.severity,
  decision: c.decision,
  ...(c.assigned_action !== undefined ? { assigned_action: c.assigned_action } : {}),
  ...(c.vendor !== undefined ? { vendor: c.vendor } : {}),
  ...(c.amount_at_risk !== undefined ? { amount_at_risk: c.amount_at_risk } : {}),
  ...(c.currency !== undefined ? { currency: c.currency } : {}),
  ...(c.triage_minutes !== undefined ? { triage_minutes: c.triage_minutes } : {}),
  created_at: c.created_at,
}));

export const demoCampaigns: Campaign[] = [
  {
    id: "camp-04",
    name: "Supply Co remittance cluster",
    severity: "critical",
    case_count: 2,
    shared_indicators: [
      "supplyco-billing.net",
      "acct ••••7741",
      "accounts.finance@supplyco-billing.net",
    ],
    first_seen: hoursAgo(31),
    last_seen: hoursAgo(3),
    case_ids: ["c-1042", "c-1039"],
    victim_teams: ["Accounts payable", "Treasury"],
    domains: ["supplyco-billing.net", "mx41.supplyco-billing.net"],
    reply_tos: ["accounts.finance@supplyco-billing.net"],
    bank_accounts: ["••••7741 — SUPPLYCO TRADING LTD"],
    attachment_hashes: ["9f2c41ab…8b1c"],
    recommended_actions: [
      "Hold all payments to Supply Co until callback verification",
      "Block supplyco-billing.net at the mail gateway",
      "Notify treasury of the fraudulent account suffix 7741",
    ],
  },
  {
    id: "camp-02",
    name: "Credential lure wave — finance mailboxes",
    severity: "high",
    case_count: 2,
    shared_indicators: ["mailquota-alerts.com", "payrollcentral-secure.com", "198.51.100.24"],
    first_seen: hoursAgo(99),
    last_seen: hoursAgo(54),
    case_ids: ["c-1035", "c-1029"],
    victim_teams: ["Finance shared services", "Payroll"],
    domains: ["mailquota-alerts.com", "payrollcentral-secure.com"],
    reply_tos: ["support@mailquota-alerts.com"],
    bank_accounts: [],
    attachment_hashes: [],
    recommended_actions: [
      "Force password reset for recipients who opened the linked page",
      "Block both lure domains and submit for takedown",
    ],
  },
  {
    id: "camp-07",
    name: "Executive wire pressure — look-alike domains",
    severity: "critical",
    case_count: 1,
    shared_indicators: ["astermanufactoring.com", "mailrelay-secure.com", "acct ••••2210"],
    first_seen: hoursAgo(9),
    last_seen: hoursAgo(9),
    case_ids: ["c-1041"],
    victim_teams: ["Treasury"],
    domains: ["astermanufactoring.com", "mailrelay-secure.com"],
    reply_tos: ["m.calder.office@mailrelay-secure.com"],
    bank_accounts: ["••••2210 — CALDER ADVISORY SERVICES"],
    attachment_hashes: [],
    recommended_actions: [
      "Register and monitor corporate domain variants",
      "Require dual approval for same-day wires above $50,000",
    ],
  },
];

export const demoVendors: VendorProfile[] = [
  {
    id: "v-1",
    name: "Supply Co Industrial",
    trusted_domains: ["supplyco.com", "mail.supplyco.com"],
    trusted_contacts: ["accounts@supplyco.com", "j.reyes@supplyco.com"],
    approved_bank_suffixes: ["4412", "8890"],
    normal_recipients: ["ap@astermanufacturing.com"],
    related_case_ids: ["c-1042", "c-1039"],
    risk_state: "at_risk",
    last_interaction: hoursAgo(3),
    relationship_since: "2019-04-01T00:00:00Z",
    anomalies: [
      { label: "Unknown bank account ••••7741", severity: "critical", at: hoursAgo(3) },
      { label: "Look-alike billing domain in use", severity: "high", at: hoursAgo(28) },
    ],
  },
  {
    id: "v-2",
    name: "Northline Freight",
    trusted_domains: ["northline-freight.com"],
    trusted_contacts: ["logistics@northline-freight.com"],
    approved_bank_suffixes: ["3320"],
    normal_recipients: ["logistics@astermanufacturing.com"],
    related_case_ids: ["c-1031"],
    risk_state: "watch",
    last_interaction: hoursAgo(78),
    relationship_since: "2021-08-15T00:00:00Z",
    anomalies: [
      { label: "Archive attachment with executable content", severity: "high", at: hoursAgo(78) },
    ],
  },
  {
    id: "v-3",
    name: "Harborline Metals",
    trusted_domains: ["harborline-metals.com"],
    trusted_contacts: ["procurement@harborline-metals.com", "ar@harborline-metals.com"],
    approved_bank_suffixes: ["1142", "1180"],
    normal_recipients: ["ap@astermanufacturing.com"],
    related_case_ids: ["c-1037"],
    risk_state: "watch",
    last_interaction: hoursAgo(40),
    relationship_since: "2020-02-10T00:00:00Z",
    anomalies: [
      { label: "Beneficiary change without prior notice", severity: "high", at: hoursAgo(40) },
    ],
  },
  {
    id: "v-4",
    name: "Meridian Utilities",
    trusted_domains: ["meridian-utilities.com"],
    trusted_contacts: ["billing@meridian-utilities.com"],
    approved_bank_suffixes: ["9032"],
    normal_recipients: ["ap@astermanufacturing.com"],
    related_case_ids: ["c-1028"],
    risk_state: "trusted",
    last_interaction: hoursAgo(120),
    relationship_since: "2016-11-05T00:00:00Z",
    anomalies: [],
  },
  {
    id: "v-5",
    name: "Kestrel Tooling",
    trusted_domains: ["kestreltooling.co"],
    trusted_contacts: ["invoices@kestreltooling.co"],
    approved_bank_suffixes: ["6640", "6641"],
    normal_recipients: ["ap@astermanufacturing.com"],
    related_case_ids: [],
    risk_state: "trusted",
    last_interaction: hoursAgo(150),
    relationship_since: "2022-06-20T00:00:00Z",
    anomalies: [],
  },
];
