ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS case_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS recommended_actions TEXT[] NOT NULL DEFAULT '{}';

ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();