import type { Case, Campaign, VendorProfile } from "../types.js";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();

export const seedVendors: VendorProfile[] = [
  {
    id: "v-1",
    name: "Supply Co Industrial",
    trusted_domains: ["supplyco.com", "mail.supplyco.com"],
    trusted_contacts: ["accounts@supplyco.com", "j.reyes@supplyco.com"],
    approved_bank_suffixes: ["4412", "8890"],
    normal_recipients: ["ap@astermanufacturing.com"],
    related_case_ids: ["c-1042", "c-1039"],
    risk_state: "at_risk",
    last_interaction: hoursAgo(3),
    relationship_since: "2019-04-01T00:00:00Z",
    anomalies: [
      { label: "Unknown bank account ••••7741", severity: "critical", at: hoursAgo(3) },
      { label: "Look-alike billing domain in use", severity: "high", at: hoursAgo(28) },
    ],
  },
  {
    id: "v-2",
    name: "Apex Global Cloud",
    trusted_domains: ["apex-global.com", "apex.cloud"],
    trusted_contacts: ["billing@apex-global.com", "ar@apex-global.com"],
    approved_bank_suffixes: ["1284", "5519"],
    normal_recipients: ["ap@astermanufacturing.com", "it-finance@astermanufacturing.com"],
    related_case_ids: ["c-1037"],
    risk_state: "at_risk",
    last_interaction: hoursAgo(18),
    relationship_since: "2021-08-15T00:00:00Z",
    anomalies: [
      { label: "Compromised genuine mailbox anomaly", severity: "critical", at: hoursAgo(18) },
      {
        label: "Unseen Reply-To address routed off-domain",
        severity: "critical",
        at: hoursAgo(18),
      },
    ],
  },
  {
    id: "v-3",
    name: "Harborline Logistics",
    trusted_domains: ["harborline-logistics.com", "harborline.example"],
    trusted_contacts: ["billing@harborline-logistics.com", "invoices@harborline-logistics.com"],
    approved_bank_suffixes: ["9821", "4401"],
    normal_recipients: ["ap@astermanufacturing.com", "finance@astermanufacturing.com"],
    related_case_ids: ["c-1038"],
    risk_state: "trusted",
    last_interaction: hoursAgo(42),
    relationship_since: "2022-01-10T00:00:00Z",
    anomalies: [],
  },
];

export const seedCases: Case[] = [
  {
    id: "c-1042",
    case_number: "SM-1042",
    subject: "Updated remittance details for invoice INV-88213",
    sender: "accounts@aster-supplyco.com",
    threat_class: "invoice_fraud",
    risk_score: 94,
    severity: "critical",
    decision: "pending",
    assigned_action: "Hold payment",
    vendor: "Supply Co Industrial",
    amount_at_risk: 184320,
    triage_minutes: 6,
    currency: "USD",
    created_at: hoursAgo(3),
    confidence: 0.96,
    decision_banner: "Hold payment recommended — vendor identity mismatch detected",
    recipients: ["ap@astermanufacturing.com"],
    body_preview:
      "Please note our banking details have changed effective immediately. Kindly remit the outstanding balance of $184,320.00 to the account below to avoid service interruption. Treat this as confidential until the transfer clears.",
    evidence: {
      intent: {
        classification: "invoice_fraud",
        model_confidence: 0.96,
        signals: [
          { label: "Banking details change request", severity: "critical", weight: 0.34 },
          { label: "Urgency pressure language", severity: "high", weight: 0.19 },
          {
            label: "Requests confidentiality until transfer clears",
            severity: "high",
            weight: 0.14,
          },
        ],
      },
      sender_identity: {
        from_address: "accounts@aster-supplyco.com",
        display_name: "Supply Co Accounts",
        reply_to: "accounts.finance@supplyco-billing.net",
        return_path: "bounce@mx41.supplyco-billing.net",
        auth: { spf: "softfail", dkim: "fail", dmarc: "fail" },
        trusted_vendor: "Supply Co Industrial",
        vendor_domain_match: false,
        notes: [
          { label: "Reply-To domain differs from From domain", severity: "critical" },
          { label: "Look-alike domain registered 11 days ago", severity: "high" },
        ],
      },
      financial: {
        invoice_amount: 184320,
        currency: "USD",
        bank_account_last4: "7741",
        bank_account_known: false,
        payment_change_requested: true,
        beneficiary: "SUPPLYCO TRADING LTD",
        notes: [{ label: "Beneficiary name differs from contracted entity", severity: "high" }],
      },
      technical: {
        urls: ["https://supplyco-billing.net/invoice/88213"],
        domains: ["supplyco-billing.net", "mx41.supplyco-billing.net"],
        relay_ips: ["45.147.230.18", "185.220.101.44"],
        attachments: [
          {
            filename: "INV-88213-revised.pdf",
            mime_type: "application/pdf",
            size_bytes: 184233,
            sha256: "9f2c41ab7d0e5b8c1a44f9e2b6d7c3018a5e4f9b2c7d1e3a6b8f0c2d4e6a8b1c",
            suspicious: true,
          },
        ],
      },
      vendor_relationship: {
        trusted_domain: "supplyco.com",
        known_contact: "accounts@supplyco.com",
        approved_bank_suffixes: ["4412", "8890"],
        normal_recipients: ["ap@astermanufacturing.com"],
      },
    },
    timeline: [
      {
        order: 1,
        title: "Bank account never seen for this vendor",
        description:
          "Account ending 7741 does not match approved suffixes 4412 or 8890 for Supply Co Industrial.",
        severity: "critical",
        weight: 0.31,
      },
      {
        order: 2,
        title: "Reply-To redirects off-domain",
        description:
          "Replies route to supplyco-billing.net, not the contracted vendor domain supplyco.com.",
        severity: "critical",
        weight: 0.24,
      },
      {
        order: 3,
        title: "Authentication failures on sending path",
        description:
          "DKIM fail, DMARC fail, SPF softfail. Message did not originate from vendor infrastructure.",
        severity: "high",
        weight: 0.18,
      },
    ],
    relay_path: [
      {
        index: 1,
        host: "mx41.supplyco-billing.net",
        ip: "45.147.230.18",
        timestamp: hoursAgo(3.1),
        suspicious: true,
      },
    ],
    campaign_id: "camp-04",
    campaign_graph: {
      nodes: [
        { id: "e1", label: "SM-1042", type: "email", suspicious: true },
        { id: "e2", label: "SM-1039", type: "email" },
        { id: "d1", label: "supplyco-billing.net", type: "domain", suspicious: true },
        { id: "r1", label: "accounts.finance@…", type: "reply_to", suspicious: true },
        { id: "b1", label: "acct ••••7741", type: "bank_account", suspicious: true },
      ],
      edges: [
        { source: "e1", target: "d1", suspicious: true },
        { source: "e1", target: "r1", suspicious: true },
        { source: "e1", target: "b1", suspicious: true },
        { source: "e2", target: "r1", suspicious: true },
      ],
    },
    actions: [],
  },
  {
    id: "c-1037",
    case_number: "SM-1037",
    subject: "RE: Monthly Cloud Hosting Statement - Urgent Payment Account Correction",
    sender: "billing@apex-global.com",
    threat_class: "invoice_fraud",
    risk_score: 91,
    severity: "critical",
    decision: "pending",
    assigned_action: "Hold payment",
    vendor: "Apex Global Cloud",
    amount_at_risk: 47800,
    triage_minutes: 11,
    currency: "USD",
    created_at: hoursAgo(18),
    confidence: 0.94,
    decision_banner:
      "Hold payment recommended — genuine account compromised; unauthorized beneficiary change",
    recipients: ["ap@astermanufacturing.com", "it-finance@astermanufacturing.com"],
    body_preview:
      "Hi Team, please find attached our updated monthly statement. Our regular depository bank is currently undergoing an annual compliance audit. Please route this month's wire payment to our secondary escrow account ending in 4401 immediately.",
    evidence: {
      intent: {
        classification: "invoice_fraud",
        model_confidence: 0.94,
        signals: [
          { label: "Deposit account diversion request", severity: "critical", weight: 0.35 },
          { label: "Audit excuse narrative", severity: "high", weight: 0.22 },
        ],
      },
      sender_identity: {
        from_address: "billing@apex-global.com",
        display_name: "Apex Billing Department",
        reply_to: "apex-billing@mail-routing.net",
        return_path: "billing@apex-global.com",
        auth: { spf: "pass", dkim: "pass", dmarc: "pass" },
        trusted_vendor: "Apex Global Cloud",
        vendor_domain_match: true,
        notes: [
          { label: "SPF and DKIM pass from legitimate vendor infrastructure", severity: "low" },
          { label: "Reply-To differs from sender address", severity: "critical" },
        ],
      },
      financial: {
        invoice_amount: 47800,
        currency: "USD",
        bank_account_last4: "4401",
        bank_account_known: false,
        payment_change_requested: true,
        beneficiary: "GLOBAL CLOUD ESCROW LLC",
        notes: [
          { label: "Escrow account not recognized in vendor approved list", severity: "critical" },
        ],
      },
      technical: {
        urls: [],
        domains: ["apex-global.com", "mail-routing.net"],
        relay_ips: ["198.51.100.14"],
        attachments: [],
      },
      vendor_relationship: {
        trusted_domain: "apex-global.com",
        known_contact: "billing@apex-global.com",
        approved_bank_suffixes: ["1284", "5519"],
        normal_recipients: ["ap@astermanufacturing.com", "it-finance@astermanufacturing.com"],
      },
    },
    timeline: [
      {
        order: 1,
        title: "Genuine mailbox compromised — SPF/DKIM pass",
        description:
          "Authentication passed from contracted vendor infrastructure. The genuine mailbox is sending fraudulent diversion instructions.",
        severity: "critical",
        weight: 0.38,
      },
      {
        order: 2,
        title: "Unapproved bank account suffix ••••4401",
        description:
          "Apex Global Cloud approved bank accounts end with 1284 and 5519. The requested account suffix 4401 is unauthorized.",
        severity: "critical",
        weight: 0.32,
      },
      {
        order: 3,
        title: "Unseen Reply-To intercepts responses",
        description:
          "Reply-To routes to mail-routing.net to prevent the genuine account owner from seeing replies.",
        severity: "critical",
        weight: 0.28,
      },
    ],
    relay_path: [
      {
        index: 1,
        host: "mail.apex-global.com",
        ip: "198.51.100.14",
        timestamp: hoursAgo(18.1),
      },
    ],
    actions: [],
  },
  {
    id: "c-1039",
    case_number: "SM-1039",
    subject: "Invoice INV-88060 — amended payment instructions",
    sender: "billing@supplyco-billing.net",
    threat_class: "invoice_fraud",
    risk_score: 87,
    severity: "critical",
    decision: "payment_held",
    assigned_action: "Payment held",
    vendor: "Supply Co Industrial",
    amount_at_risk: 61240,
    triage_minutes: 34,
    currency: "USD",
    created_at: hoursAgo(28),
    confidence: 0.9,
    decision_banner: "Payment held — bank account not on the approved vendor list",
    recipients: ["ap@astermanufacturing.com"],
    body_preview:
      "Kindly find amended payment instructions for invoice INV-88060. Our previous account is under audit.",
    evidence: {
      intent: {
        classification: "invoice_fraud",
        model_confidence: 0.9,
        signals: [{ label: "Amended payment instructions", severity: "critical", weight: 0.3 }],
      },
      sender_identity: {
        from_address: "billing@supplyco-billing.net",
        reply_to: "accounts.finance@supplyco-billing.net",
        auth: { spf: "fail", dkim: "fail", dmarc: "fail" },
        trusted_vendor: "Supply Co Industrial",
        vendor_domain_match: false,
      },
      financial: {
        invoice_amount: 61240,
        currency: "USD",
        bank_account_last4: "7741",
        bank_account_known: false,
        payment_change_requested: true,
        beneficiary: "SUPPLYCO TRADING LTD",
      },
      technical: {
        urls: ["https://supplyco-billing.net/pay/88060"],
        domains: ["supplyco-billing.net"],
        relay_ips: ["45.147.230.18"],
        attachments: [],
      },
      vendor_relationship: {
        trusted_domain: "supplyco.com",
        known_contact: "accounts@supplyco.com",
        approved_bank_suffixes: ["4412", "8890"],
        normal_recipients: ["ap@astermanufacturing.com"],
      },
    },
    timeline: [
      {
        order: 1,
        title: "Amended payment instructions",
        description: "Attacker requested change of beneficiary.",
        severity: "critical",
        weight: 0.3,
      },
    ],
    relay_path: [
      {
        index: 1,
        host: "mx41.supplyco-billing.net",
        ip: "45.147.230.18",
        timestamp: hoursAgo(28.1),
        suspicious: true,
      },
    ],
    campaign_id: "camp-04",
    actions: [],
  },
  {
    id: "c-1038",
    case_number: "SM-1038",
    subject: "Vendor profile confirmation — quarterly compliance",
    sender: "compliance@harborline-logistics.com",
    threat_class: "benign",
    risk_score: 12,
    severity: "safe",
    decision: "safe",
    assigned_action: "Approved",
    vendor: "Harborline Logistics",
    triage_minutes: 5,
    created_at: hoursAgo(54),
    confidence: 0.98,
    decision_banner: "Safe — routine verification from authentic vendor address",
    recipients: ["finance@astermanufacturing.com"],
    body_preview: "Please review the attached quarterly vendor compliance certificate.",
    evidence: {
      intent: { classification: "benign", model_confidence: 0.98, signals: [] },
      sender_identity: {
        from_address: "compliance@harborline-logistics.com",
        auth: { spf: "pass", dkim: "pass", dmarc: "pass" },
        trusted_vendor: "Harborline Logistics",
        vendor_domain_match: true,
      },
      financial: {},
      technical: {
        urls: [],
        domains: ["harborline-logistics.com"],
        relay_ips: [],
        attachments: [],
      },
      vendor_relationship: {
        trusted_domain: "harborline-logistics.com",
        known_contact: "billing@harborline-logistics.com",
        approved_bank_suffixes: ["9821", "4401"],
        normal_recipients: ["finance@astermanufacturing.com"],
      },
    },
    timeline: [
      {
        order: 1,
        title: "Authenticated sender",
        description: "SPF/DKIM/DMARC all pass.",
        severity: "safe",
        weight: 0.1,
      },
    ],
    relay_path: [],
    actions: [],
  },
  {
    id: "c-1035",
    case_number: "SM-1035",
    subject: "Action required: Mailbox storage quota exceeded",
    sender: "admin@mailquota-alerts.com",
    threat_class: "credential_phishing",
    risk_score: 84,
    severity: "critical",
    decision: "escalated",
    assigned_action: "Quarantine & reset",
    triage_minutes: 14,
    created_at: hoursAgo(99),
    confidence: 0.92,
    decision_banner: "Critical credential phishing lure detected targeting finance accounts",
    recipients: ["ap@astermanufacturing.com"],
    body_preview:
      "Your mailbox has reached 98% capacity. Click below to verify and prevent message rejection.",
    evidence: {
      intent: {
        classification: "credential_phishing",
        model_confidence: 0.92,
        signals: [{ label: "Mailbox quota lure", severity: "high", weight: 0.25 }],
      },
      sender_identity: {
        from_address: "admin@mailquota-alerts.com",
        auth: { spf: "fail", dkim: "none", dmarc: "fail" },
      },
      financial: {},
      technical: {
        urls: ["https://mailquota-alerts.com/login"],
        domains: ["mailquota-alerts.com"],
        relay_ips: ["198.51.100.24"],
        attachments: [],
      },
    },
    timeline: [
      {
        order: 1,
        title: "Credential harvesting link",
        description: "Fake login page detected.",
        severity: "critical",
        weight: 0.35,
      },
    ],
    relay_path: [],
    campaign_id: "camp-02",
    actions: [],
  },
  {
    id: "c-1041",
    case_number: "SM-1041",
    subject: "Confidential wire instructions — M&A legal advisory",
    sender: "ceo@astermanufactoring.com",
    threat_class: "ceo_impersonation",
    risk_score: 95,
    severity: "critical",
    decision: "payment_held",
    assigned_action: "Hold payment",
    amount_at_risk: 120000,
    currency: "USD",
    triage_minutes: 7,
    created_at: hoursAgo(140),
    confidence: 0.96,
    decision_banner: "Hold payment recommended — executive impersonation on look-alike domain",
    recipients: ["treasury@astermanufacturing.com"],
    body_preview: "Please execute the urgent $120,000 wire to our retained counsel immediately.",
    evidence: {
      intent: {
        classification: "ceo_impersonation",
        model_confidence: 0.96,
        signals: [{ label: "CEO wire request", severity: "critical", weight: 0.35 }],
      },
      sender_identity: {
        from_address: "ceo@astermanufactoring.com",
        reply_to: "m.calder.office@mailrelay-secure.com",
        auth: { spf: "fail", dkim: "fail", dmarc: "fail" },
      },
      financial: {
        invoice_amount: 120000,
        currency: "USD",
        bank_account_last4: "2210",
        payment_change_requested: true,
      },
      technical: {
        urls: [],
        domains: ["astermanufactoring.com"],
        relay_ips: ["185.220.101.5"],
        attachments: [],
      },
    },
    timeline: [
      {
        order: 1,
        title: "Typosquatted domain",
        description: "astermanufactoring.com vs astermanufacturing.com",
        severity: "critical",
        weight: 0.35,
      },
    ],
    relay_path: [],
    actions: [],
  },
];

export const seedCampaigns: Campaign[] = [
  {
    id: "camp-04",
    name: "Supply Co remittance cluster",
    severity: "critical",
    case_count: 2,
    shared_indicators: [
      "supplyco-billing.net",
      "acct ••••7741",
      "accounts.finance@supplyco-billing.net",
    ],
    first_seen: hoursAgo(31),
    last_seen: hoursAgo(3),
    case_ids: ["SM-1042", "SM-1039"],
    victim_teams: ["Accounts payable", "Treasury"],
    domains: ["supplyco-billing.net", "mx41.supplyco-billing.net"],
    reply_tos: ["accounts.finance@supplyco-billing.net"],
    bank_accounts: ["••••7741 — SUPPLYCO TRADING LTD"],
    attachment_hashes: ["9f2c41ab…8b1c"],
    recommended_actions: [
      "Hold all payments to Supply Co until callback verification",
      "Block supplyco-billing.net at the mail gateway",
      "Notify treasury of the fraudulent account suffix 7741",
    ],
  },
  {
    id: "camp-02",
    name: "Credential lure wave — finance mailboxes",
    severity: "high",
    case_count: 2,
    shared_indicators: ["mailquota-alerts.com", "payrollcentral-secure.com", "198.51.100.24"],
    first_seen: hoursAgo(99),
    last_seen: hoursAgo(54),
    case_ids: ["SM-1035", "SM-1029"],
    victim_teams: ["Finance shared services", "Payroll"],
    domains: ["mailquota-alerts.com", "payrollcentral-secure.com"],
    reply_tos: ["support@mailquota-alerts.com"],
    bank_accounts: [],
    attachment_hashes: [],
    recommended_actions: [
      "Force password reset for recipients who opened the linked page",
      "Block both lure domains and submit for takedown",
    ],
  },
];
